### ISSUE TITLE
Update dependencies to datacube >=1.8.12?

### ISSUE THREAD

**Issue by pjonsson** [opendatacube/datacube-docker#108]
Commit 934f0d8 by @omad requires datacube 1.8.9 to avoid https://github.com/opendatacube/datacube-core/issues/1412.

Since the transaction isolation level was reduced in 1.8.12, is it possible to un-restrict the datacube version again?

**Comment by benjimin** [comment]
Linking to https://github.com/opendatacube/odc-tools/issues/582

**Comment by omad** [comment]
I'm working on updating this datacube-index docker image. It's quite a lot out of date, and I'm not in <3 with the way it's built, but I'm trying not to completely reinvent it...

Watch this space.

**Comment by omad** [comment]
A new `opendatacube/datacube-index:0.3.0` docker image is available.

https://hub.docker.com/r/opendatacube/datacube-index


![image](https://github.com/opendatacube/datacube-docker/assets/108979/261fd2e0-8c66-4120-9711-a5b5e904632c)

**Comment by pjonsson** [comment]
Thank you for fixing this!

> I'm working on updating this datacube-index docker image. It's quite a lot out of date, and I'm not in <3 with the way it's built, but I'm trying not to completely reinvent it...

It's been a while since I looked at the Dockerfile, but I think I saw some things that I could fix with a rather low effort, do you want pull requests?
