### ISSUE TITLE
Make 0.3.3 release?

### ISSUE THREAD

**Issue by pjonsson** [opendatacube/datacube-docker#140]
I just noticed #138 updates version.txt, so perhaps there should be a corresponding 0.3.3 release?

**Comment by alexgleith** [comment]
Really we should refactor the process so that it doesn't rely on the version.txt file. Currently it still does.

**Comment by pjonsson** [comment]
@alexgleith I made a 0.3.3 release draft, please check/edit it and publish when you think it is fine.
