### ISSUE TITLE
Improvements for GitHub Actions

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-docker#35]
At the moment, it looks like images are built and pushed to docker hub even when the testing action fails.

Is this the intended behaviour?

To me, it looks like we should combine the `test` and `push` Actions, to only push an image after tests have run successfully.

**Comment by alexgleith** [comment]
It only pushes from `main`, so presumably test are passing in the PR before it merges to main...

But yeah, good point.

**Comment by alexgleith** [comment]
I think this is done now.
